### ISSUE TITLE
Wei from Eth return 0 for decimal value

### ISSUE THREAD

**Issue by mdevo** [web3-php/web3#21]
$wei = Wei::fromEth('0.01');

Results:
Web3\ValueObjects\Wei^ {#874
  -value: "0"
}

**Comment by mdevo** [comment]
Perhaps could use BC Math functions: https://www.php.net/manual/en/ref.bc.php

**Comment by owenvoke** [comment]
The current implementation uses `phpseclib/phpseclib`'s Math classes, which will fall back to the BCMath or GMP functions if they're available, and otherwise use a userland implementation. However, I was able to reproduce this issue, both with BCMath and GMP. I'm currently not able to test the userland implementation as I'm on Windows atm which ~~always has BCMath enabled by default~~. Actually, it looks like it will use [the `PHP64` implementation](https://github.com/phpseclib/phpseclib/blob/92b0261c0c0a04dac7acb038b64149cbff881950/phpseclib/Math/BigInteger/Engines/PHP64.php) [before BCMath if you are using PHP 64-bit](https://github.com/phpseclib/phpseclib/blob/92b0261c0c0a04dac7acb038b64149cbff881950/phpseclib/Math/BigInteger.php#L154). I just manually forced BCMath to be used first and the same applies. It seems that none of the implementations have the correct output.

I guess it is `BigInteger`, which probably doesn't support floats (at least going from the name), so it might be worth us adding `fromGwei`, etc. implementations as per the `toX()` methods.

Actually, I just noticed that you can just do `new Wei('10000000000000000')` to get the same `0.01 ETH` you're wanting.
